# pull official base image
FROM node:12.22.9

# set working directory
WORKDIR /app
RUN npm install -g npm@8.5.1

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --silent
RUN npm install react-scripts@3.4.1 -g
RUN npm install -g peer-dependencies

# add app
COPY . ./

# start app
CMD ["npm", "start"]