name: Build Waiting Time Analysis Client

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.22.9 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm version 8.5.1
        run: npm install -g npm@8.5.1
        
      - name: Install dependencies
        run: npm ci

      - name: Run the tests
        run: npm test --if-present

      - name: Build
        run: npm run build --if-present
